title = "Custom Gitleaks Config for Flask App"
[[rules]]
description = "Flask Secret Key"
regex = '''(?i)app\.secret[_\-]?key\s*=\s*['"][^'"]+['"]'''
tags = ["secret", "flask", "key"]

[[rules]]
description = "Potential API Key or Token"
regex = '''(?i)(api[_\-]?key|token)\s*=\s*['"][a-zA-Z0-9_\-]{16,}['"]'''
tags = ["secret", "apikey", "token"]

[[rules]]
description = "Generic Key or Credential"
regex = '''(?i)(key|credential|secret)\s*=\s*['"][^'"]+['"]'''
tags = ["secret", "generic"]

[[rules]]
description = "Hardcoded Username"
regex = '''(?i)\b(admin[_\-]?username|user[_\-]?name)\s*=\s*['"][^'"]{3,}['"]'''
tags = ["secret", "username"]

[[rules]]
description = "Hardcoded Password"
regex = '''(?i)\b(admin[_\-]?password|pass[_\-]?word)\s*=\s*['"][^'"]{6,}['"]'''
tags = ["secret", "password"]
