name: gitleaks
on:
  push:
    branches:
      - '**'  # now set to all branches, but can be set to for example just main
  pull_request:
    branches:
      - '**'  # now set to all branches, but can be set to for example just main
  workflow_dispatch:  # This is for manual running workflow from github site
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
